sudo: required
services:
    - docker

before_install:
    - docker build -t marcuspaget/demoPipeLine -f Dockerfile.dev .

script:
    - docker run marcuspaget/demoPipeLine npm run test -- --coverage
